name: hadirproteacher
description: "The Teacher desktop app for HadirPro.."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bitsdojo_window: ^0.1.6
  fluent_ui: ^4.10.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  hadir_core: 0.0.1
  hadir_ui: 0.0.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  sizer: ^3.0.5
  supabase_flutter: ^2.8.3
  system_theme: ^3.1.2
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svgs/
