include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    always_put_required_named_parameters_first: ignore
    inference_failure_on_instance_creation: ignore
    lines_longer_than_80_chars: ignore
    unnecessary_lambdas: ignore

  plugins:
    - custom_lint

  exclude:
    - "build/**"
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    public_member_api_docs: false
