name: hadir_core
description: "The Core package for HadirPro."
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  pretty_qr_code: ^3.3.0
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^2.8.2

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^7.0.0
